Repository osdlyrics/osdlyrics, pull requests merged in 2019-03, with the labels that each got.

#56 Adopt GitHub Flow & Discord
  ABOUT-NLS
  AUTHORS
  ChangeLog
  INSTALL
  LICENSE
  NEWS
  README
  README.md
  ROADMAP.md
  screenshot.png
Labels: enhancement

#57 Python: fix NULL ending in downloaded lrc
  daemon/lyrics.py
Labels: bug, enhancement

#58 Fixes autoreconf with "foreign" flag
  configure.ac
Labels: bug
